// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlXWO9ZL-cBpaJE7tZ6sMZCdQrkstZNlk',
    appId: '1:112248796042:web:0a3e5ec971c64b5eb14e73',
    messagingSenderId: '112248796042',
    projectId: 'zomato-3354a',
    authDomain: 'zomato-3354a.firebaseapp.com',
    storageBucket: 'zomato-3354a.firebasestorage.app',
    measurementId: 'G-HSD34P3GXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_IFJ6NZxj4yV2DV_iMiiUujCedw8K4ZY',
    appId: '1:112248796042:android:71a21ca27d019a45b14e73',
    messagingSenderId: '112248796042',
    projectId: 'zomato-3354a',
    storageBucket: 'zomato-3354a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL3NmIArs9xVdSvfQjSOWi7NX1lI3lJ58',
    appId: '1:112248796042:ios:1807d605cb13afcdb14e73',
    messagingSenderId: '112248796042',
    projectId: 'zomato-3354a',
    storageBucket: 'zomato-3354a.firebasestorage.app',
    androidClientId: '112248796042-9l8j4ri75gqvkgenoj548gkdntumkd8c.apps.googleusercontent.com',
    iosClientId: '112248796042-rkog6v193j64ka34saujcnmb1a6s01eh.apps.googleusercontent.com',
    iosBundleId: 'com.app.onlineSwissy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL3NmIArs9xVdSvfQjSOWi7NX1lI3lJ58',
    appId: '1:112248796042:ios:1807d605cb13afcdb14e73',
    messagingSenderId: '112248796042',
    projectId: 'zomato-3354a',
    storageBucket: 'zomato-3354a.firebasestorage.app',
    androidClientId: '112248796042-9l8j4ri75gqvkgenoj548gkdntumkd8c.apps.googleusercontent.com',
    iosClientId: '112248796042-rkog6v193j64ka34saujcnmb1a6s01eh.apps.googleusercontent.com',
    iosBundleId: 'com.app.onlineSwissy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlXWO9ZL-cBpaJE7tZ6sMZCdQrkstZNlk',
    appId: '1:112248796042:web:f40948d54e80e2feb14e73',
    messagingSenderId: '112248796042',
    projectId: 'zomato-3354a',
    authDomain: 'zomato-3354a.firebaseapp.com',
    storageBucket: 'zomato-3354a.firebasestorage.app',
    measurementId: 'G-RSLFPSGFY0',
  );
}
